version: "3"

services:
  my-redis:
    image: redis:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "redis.host": "my-redis",
        "redis.port": "6379"
      }'
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.rabbitmq.host":"rabbitmq",
      "spring.rabbitmq.port":"5672",
      "spring.rabbitmq.management.port": "15672",
      "spring.rabbitmq.username":"guest",
      "spring.rabbitmq.password":"guest",
      "backend.rabbitmq.exchange":"backend.exchange",
      "backend.rabbitmq.queue":"backend.queue",
      "backend.rabbitmq.routingkey":"backend.routingkey"
      }'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
      - my-redis
      - rabbitmq
    build: ./
    restart: on-failure
    env_file: ./.env
    ports :
      - 9090:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.liquibase.change-log" : "classpath:db/changelog/db-changelog.xml",
        "redis.host": "my-redis",
        "redis.port": "6379",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"5672",
        "spring.rabbitmq.management.port": "15672",
        "spring.rabbitmq.username":"guest",
        "spring.rabbitmq.password":"guest",
        "backend.rabbitmq.exchange":"backend.exchange",
        "backend.rabbitmq.queue":"backend.queue",
        "backend.rabbitmq.routingkey":"backend.routingkey"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  redis_volume:
    driver: local
  rabbitmq_volume:
    driver: local

